name: Artifact release

on:
  workflow_dispatch:
    inputs:
      original_tag:
        required: true


permissions:
  contents: write
  actions: read

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: "${{ inputs.original_tag }}"

    - name: Create and push artifact tag
      run: |
        git tag "${{ inputs.original_tag }}-artifacts"
        git push origin "${{ inputs.original_tag }}-artifacts"

  build:
    needs: tag
    uses: ShinySaana/dcgm-exporter/.github/workflows/go.yml@release
    with:
      commitish: "${{ inputs.original_tag }}-artifacts"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tag
        run: |
          echo "ARTIFACT_TAG=${{ inputs.original_tag }}-artifacts" >> $GITHUB_ENV

      - name: Get original tag
        id: original_tag
        run: |
          echo ORIGINAL_TAG="${{ inputs.original_tag }}" >> $GITHUB_ENV

      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

          run-id: ${{ needs.build.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -R /tmp/artifacts

      - name: Create draft release
        run: |
          gh release create \
            --repo ${{ github.repository }} \
            --draft \
            --notes 'See the [original release](https://github.com/NVIDIA/dcgm-exporter/releases/tag/${{ env.ORIGINAL_TAG }}).' \
            --title "${{ env.ORIGINAL_TAG }}" \
            --verify-tag \
            "${{ env.ARTIFACT_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload linux-amd64 artifact
        run: |
          gh release upload \
            --repo ${{ github.repository }} \
            "${{ env.ARTIFACT_TAG }}" \
            /tmp/artifacts/dcgm-exporter.linux-amd64.tar.gz/dcgm-exporter-${{ env.ORIGINAL_TAG }}.linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        run: |
          gh release edit \
            --draft=false \
            --repo ${{ github.repository }} \
            "${{ env.ARTIFACT_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
